import { AccountType, Transaction } from "../../types/types";

export const fakeTransactions:Transaction[] = [
    { id: 1, account: 'checking', date: '2024-06-12', description: 'Direct Deposit', type: 'deposit', amount: 3200 },
    { id: 2, account: 'checking', date: '2024-06-10', description: 'Utility Payment', location: 'City Power', type: 'withdrawal', amount: -185.4 },
    { id: 3, account: 'checking', date: '2024-06-08', description: 'Coffee Run', location: 'Crescent Coffee', type: 'withdrawal', amount: -14.25 },
    { id: 4, account: 'checking', date: '2024-06-03', description: 'Grocery Pickup', location: 'Market District', type: 'withdrawal', amount: -126.9 },
    { id: 5, account: 'checking', date: '2024-05-29', description: 'Online Transfer', type: 'transfer', amount: -500 },
    { id: 6, account: 'checking', date: '2024-05-27', description: 'Incoming Transfer', type: 'deposit', amount: 250 },
    { id: 7, account: 'checking', date: '2024-05-21', description: 'Dining Out', location: 'The Blue Olive', type: 'withdrawal', amount: -62.18 },
    { id: 8, account: 'checking', date: '2024-05-18', description: 'ATM Withdrawal', location: 'Downtown Branch', type: 'withdrawal', amount: -120 },
    { id: 9, account: 'checking', date: '2024-05-14', description: 'Mobile Deposit', location: 'Remote Check', type: 'deposit', amount: 410 },
    { id: 10, account: 'savings', date: '2024-06-01', description: 'Transfer from Checking', type: 'deposit', amount: 500 },
    { id: 11, account: 'savings', date: '2024-05-15', description: 'Monthly Interest', type: 'deposit', amount: 8.73 },
    { id: 12, account: 'savings', date: '2024-05-02', description: 'Transfer to Checking', type: 'transfer', amount: -300 },
    { id: 13, account: 'savings', date: '2024-04-17', description: 'Emergency Fund Deposit', type: 'deposit', amount: 1000 },
    { id: 14, account: 'savings', date: '2024-03-30', description: 'Vacation Withdrawal', type: 'withdrawal', amount: -450 },
    { id: 15, account: 'credit', date: '2024-06-11', description: 'Online Purchase', location: 'TechStop', type: 'withdrawal', amount: -349.99 },
    { id: 16, account: 'credit', date: '2024-06-09', description: 'Gas Station', location: 'Fuel Express', type: 'withdrawal', amount: -68.45 },
    { id: 17, account: 'credit', date: '2024-06-05', description: 'Payment Received', type: 'deposit', amount: 600 },
    { id: 18, account: 'credit', date: '2024-05-28', description: 'Grocery Delivery', location: 'QuickGrocer', type: 'withdrawal', amount: -96.5 },
    { id: 19, account: 'credit', date: '2024-05-18', description: 'Streaming Services', location: 'BundlePay', type: 'withdrawal', amount: -42.97 },
    { id: 20, account: 'credit', date: '2024-05-10', description: 'Balance Transfer', type: 'transfer', amount: -200 },
    { id: 21, account: 'checking', date: '2024-04-28', description: 'Insurance Refund', type: 'deposit', amount: 120.35 },
    { id: 22, account: 'checking', date: '2024-04-15', description: 'Charity Donation', location: 'Community Care', type: 'withdrawal', amount: -75 },
    { id: 23, account: 'savings', date: '2024-04-05', description: 'Round-up Transfer', type: 'deposit', amount: 35.42 },
    { id: 24, account: 'credit', date: '2024-03-15', description: 'Travel Booking', location: 'Skybound Airlines', type: 'withdrawal', amount: -520.75 },
    { id: 25, account: 'checking', date: '2024-03-01', description: 'Tax Refund', type: 'deposit', amount: 1435.66 },
    { id: 26, account: 'checking', date: '2024-02-22', description: 'Concert Tickets', location: 'City Arena', type: 'withdrawal', amount: -210 },
    { id: 27, account: 'checking', date: '2024-02-14', description: 'Payday Deposit', type: 'deposit', amount: 3200 },
    { id: 28, account: 'checking', date: '2024-01-30', description: 'Home Supplies', location: 'Hardware Hub', type: 'withdrawal', amount: -89.5 },
    { id: 29, account: 'checking', date: '2024-01-10', description: 'Gym Membership', location: 'Pulse Fitness', type: 'withdrawal', amount: -59.99 },
    { id: 30, account: 'checking', date: '2023-12-18', description: 'Holiday Bonus', type: 'deposit', amount: 750 },
    { id: 31, account: 'savings', date: '2024-06-12', description: 'Emergency Fund Boost', type: 'deposit', amount: 600 },
    { id: 32, account: 'savings', date: '2024-05-30', description: 'Vacation Transfer', type: 'withdrawal', amount: -300 },
    { id: 33, account: 'savings', date: '2024-05-10', description: 'Interest Payout', type: 'deposit', amount: 9.12 },
    { id: 34, account: 'savings', date: '2024-04-22', description: 'Round-up Transfer', type: 'deposit', amount: 24.77 },
    { id: 35, account: 'savings', date: '2024-03-12', description: 'Car Repair Fund', type: 'deposit', amount: 450 },
    { id: 36, account: 'savings', date: '2024-02-05', description: 'Unexpected Expense', type: 'withdrawal', amount: -275 },
    { id: 37, account: 'savings', date: '2024-01-15', description: 'Transfer to Checking', type: 'transfer', amount: -150 },
    { id: 38, account: 'credit', date: '2024-06-13', description: 'Electronics Purchase', location: 'Gadget World', type: 'withdrawal', amount: -1299.99 },
    { id: 39, account: 'credit', date: '2024-06-02', description: 'Restaurant', location: 'Olive & Oak', type: 'withdrawal', amount: -84.2 },
    { id: 40, account: 'credit', date: '2024-05-25', description: 'Payment Received', type: 'deposit', amount: 700 },
    { id: 41, account: 'credit', date: '2024-05-12', description: 'Subscription Bundle', location: 'StreamHub', type: 'withdrawal', amount: -54.99 },
    { id: 42, account: 'credit', date: '2024-04-27', description: 'Transfer to Savings', type: 'transfer', amount: -150 },
    { id: 43, account: 'credit', date: '2024-04-10', description: 'Home Decor', location: 'Cozy Living', type: 'withdrawal', amount: -220.45 },
    { id: 44, account: 'credit', date: '2024-03-05', description: 'Payment Received', type: 'deposit', amount: 550 },
    { id: 45, account: 'credit', date: '2024-02-14', description: 'Travel Booking', location: 'Skybound Airlines', type: 'withdrawal', amount: -780.25 },
  ]
export const accountTypes: AccountType[] = ['checking', 'savings', 'credit'];
